### ISSUE TITLE
Just a question…why Ponos and not basho_bench?

### ISSUE THREAD

**Issue by russelldb** [klarna/ponos#10]
Just wondering what lead to the creation of another load testing application.

**Comment by jool** [comment]
If I remember correctly there were two main reasons. The ability to model more complex load patterns than just calls per second was one (see the load specs for details of what ponos can do). Also, at the time, basho bench appeared a bit cumbersome to work with and we wanted a bit simpler and straightforward lib to include in our system test framework.

**Comment by russelldb** [comment]
That's great. Thanks for taking the time to answer. I'll close the issue.
Cheers
Russell
