### ISSUE TITLE
The project name sounds very funny in russian

### ISSUE THREAD

**Issue by greyblake** [klarna/ponos#11]
Hi.
I am not user of the project. I saw the project in the github's timeline, and the name attracted my attention.
I want to let you know, that in russian word `ponos` means something like diarrhea: https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%9F%D0%BE%D0%BD%D0%BE%D1%81
The word has kind of negative connotation . For a russian speaker it's funny yet very strange name.

Just for your info.
Please close the issue after reading :)

**Comment by zmstone** [comment]
duplicates #2 

haha funny.

Consider clarify it in README so people can stop reporting such issues.

**Comment by llelf** [comment]
> Consider clarify it in README

consider reading it

**Comment by zmstone** [comment]
Seriously, consider clarifying that it’s a known fact that it means diarrhea in RU, and leave it alone!

**Comment by jool** [comment]
> Seriously, consider clarifying that it’s a known fact that it means diarrhea in RU, and leave it alone!

It already is clarified 🤗 https://github.com/klarna/ponos/blob/master/README.md#ref1

**Comment by zmstone** [comment]
Alright, it’s at the bottom.
